### ISSUE TITLE
gnet引用不到NewClient方法

### ISSUE THREAD

**Issue by Eric-LBJ** [gnet-io/gnet-examples#19]
![image](https://user-images.githubusercontent.com/45961910/191709529-2364e7d2-0353-4f9c-8bd7-8caad8c580d6.png)

**Comment by Eric-LBJ** [comment]
![image](https://user-images.githubusercontent.com/45961910/191709791-c50071d0-4190-4b0c-a4ee-6846b36ef9e9.png)

**Comment by panjf2000** [comment]
你是 Windows 系统吧，v2 之后不支持 Windows 了。
