### ISSUE TITLE
不支持windows么？

### ISSUE THREAD

**Issue by ayamzh** [gnet-io/gnet-examples#26]
enine.go好像只能在linux下运行

**Comment by panjf2000** [comment]
支持 Windows，你是在 Windows 运行之后报错了？把错误信息贴上来啊

**Comment by ayamzh** [comment]
![image](https://github.com/gnet-io/gnet-examples/assets/20828679/59773622-18b5-4dfa-8e2e-70a15c0de3a8)
@panjf2000

**Comment by ayamzh** [comment]
//go:build linux || freebsd || dragonfly || darwin
// +build linux freebsd dragonfly darwin

package gnet

import (
	"context"
	"runtime"
	"sync"
	"sync/atomic"

	"github.com/panjf2000/gnet/v2/internal/netpoll"
	"github.com/panjf2000/gnet/v2/pkg/errors"
)

type engine struct {

**Comment by panjf2000** [comment]
Windows 版 gnet 要到 v2.3 才支持，当前版本是 v2.0.0，所以有这个问题，现在已更新到 v2.5.7，应该可以了，请拉取最新的代码再试试。
