### ISSUE TITLE
HTTP parser should be created for each request

### ISSUE THREAD

**Issue by binarylogic** [gnet-io/gnet-examples#27]
In the example, the wildcat HTTP parser is [created on connection open](https://github.com/gnet-io/gnet-examples/blob/d405b600693657b6857fba57e359735c61df6580/http/http.go#L44) and reused for each request. This doesn't reset the parser's state between requests, which could result in it returning the incorrect value. For example, the `ContentLength` method is cached and not reset. Am I missing something?

**Comment by panjf2000** [comment]
The wildcat HTTP parser ought to be connection-wide, check out [how the author uses it](https://github.com/evanphx/wildcat/blob/master/server.go#L43-L74).

That being said, I think you're right about the issue of caching `ContentLength`, I'm going to take a speculation and say that the author might have misinterpreted the concept.

We need to fix this issue. Good catch on this, thanks!
